-- Login has been added to the Client -- many client Code has been changed BUT: there is a Race Condition over the StrongHold and Tauri webview over Config; when you logout if you suddenly Reload the page (while app is setting Primary-User as Null to prevent an Auto-loggin) you'll get two warnings:
[Warning] IPC custom protocol failed, Tauri will now use the postMessage interface instead – TypeError: Load failed (user-script:3, line 106)
TypeError: Load failed
[Debug] [vite] connecting... (client, line 733)
[Debug] [vite] connected. (client, line 827)
[Warning] [TAURI] Couldn't find callback id 919561030. This might happen when the app is reloaded while Rust is running an asynchronous operation. (user-script:5, line 286)